FinalProject/webapp/application/controllers/edit_profile.py
from flask import session, render_template, request, redirect, Blueprint


edit = Blueprint('edit', __name__, static_folder='static')


@edit.route('/edit', methods=['GET'])
def root():
    if request.method == 'GET':
        if 'user' in session:
            user_data = session['user']
            print(user_data)
            return render_template('edit_profile.html', user_data=user_data)
        else:
            # take user to home page
            return render_template('index.html')

FinalProject/webapp/application/controllers/login.py
from flask import session, render_template, request, redirect, Blueprint, url_for
import requests
import json
from bson import json_util


login = Blueprint('login', __name__, static_folder='static')


@login.route('/login', methods=['GET', 'POST'])
def root():
    if request.method == 'GET':
        if 'user' in session:
            return render_template('trending.html')
        else:
            # take user to home page
            return render_template('login.html')
    if request.method == 'POST':
        # get users email from user input
        email = request.form.get('email')
        pw = request.form.get('password')
        # get users first name from user inpu
        LOGIN_ENDPOINT = 'http://0.0.0.0:8000/login'
        LOGIN_PARAMS = {'email': email, 'password': pw}
        l = requests.post(url=LOGIN_ENDPOINT, json=LOGIN_PARAMS)
        if l.status_code == 200:
            token = l.json()['token']
            # post token to user detail endpoint and create a session
            headers = {'content-type': 'application/json', 'token': token}

            USER_DETAIL_ENPOINT = 'http://0.0.0.0:8000/user'
            x = requests.get(url=USER_DETAIL_ENPOINT, headers=headers)
            data = x.json()['success']
            user_data = {
                'email':  data['email'],
                'fullname': data['fullname'],
                'premium':  data['premium'],
                'uuid': data['uuid'],
                'token': token
            }
            print(token)
            print(user_data)
            session['user'] = json.loads(json_util.dumps(user_data))
            return redirect(url_for('dashboard.root'))
        else:
            return redirect(url_for('index.index'))

    else:
        return render_template('login.html')

FinalProject/webapp/application/controllers/signup.py
from flask import url_for, render_template, request, redirect, Blueprint, jsonify, session
import json
import requests
from bson import json_util

signup = Blueprint('signup', __name__, static_folder='static')


@signup.route('/signup', methods=['POST'])
def root():

    if request.method == 'POST':
        # get users email from user input
        full_name = request.form.get('fullname')
        email = request.form.get('email')
        pw = request.form.get('password')
        # get users first name from user input
        first_name = request.form.get('firstname')
        # create a user
        CREATE_ENDPOINT = 'http://0.0.0.0:8000/create'
        # params to send to api
        PARAMS = {'email': email, 'fullname': full_name, 'password': pw}
        r = requests.post(url=CREATE_ENDPOINT, json=PARAMS)
        # if the request is valid with the new credentials log the user in and grab token
        if r.status_code == 200:
            LOGIN_ENDPOINT = 'http://0.0.0.0:8000/login'
            LOGIN_PARAMS = {'email': email, 'password': pw}
            l = requests.post(url=LOGIN_ENDPOINT, json=LOGIN_PARAMS)
            token = l.json()['token']
            # post token to user detail endpoint and create a session
            headers = {'content-type': 'application/json', 'token': token}
            USER_DETAIL_ENPOINT = 'http://0.0.0.0:8000/user'
            x = requests.get(url=USER_DETAIL_ENPOINT, headers=headers)
            data = x.json()['success']
            user_data = {
                'email':  data['email'],
                'fullname': data['fullname'],
                'premium':  data['premium'],
                'uuid': data['uuid'],
                'token': token
            }
            session['user'] = json.loads(json_util.dumps(user_data))

        return redirect(url_for('index.index'))
    else:
        return render_template('index.html')

FinalProject/webapp/application/controllers/user_profile.py
from flask import session, render_template, request, redirect, Blueprint


profile = Blueprint('profile', __name__, static_folder='static')


@profile.route('/profile', methods=['GET'])
def root():
    if request.method == 'GET':
        if 'user' in session:
            user_data = session['user']
            print(user_data)
            return render_template('user_profile.html', user_data=user_data)
        else:
            # take user to home page
            return render_template('index.html')

FinalProject/webapp/application/templates/index.html
<!DOCTYPE html>
<html lang="en">

<meta http-equiv="content-type" content="text/html;charset=UTF-8" />

<head>

  <link href="static/styles.css" rel="stylesheet">
</head>

<body>
  <div class="modal">
    <button type="button" class="modal-close modal-toggle"><i class="icon" data-feather="x"></i><span
        class="hide-mobile">ESC</span></button>
    <div class="modal-content">
      <div class="success">
        <a href="{{url_for('index.index')}}" class="logo"></a>
        <h2 class="modal-title first-name" id="title-name"></h2>
        <p>Thanks for signing up!</p>
        <a href="{{url_for('index.index')}}" class="button">Go to dashboard</a>
      </div>
      <div class="form-content">
        <a href="{{url_for('index.index')}}" class="logo"></a>
        <h2 class="modal-title">Join the Spyyder Community</h2>

        <center>
          <p class="modal-subtitle">We are in the early stages, try out the application now! We love feedback!</p>
        </center>
        <form class='form' name='Spyyder' action="{{url_for('signup.root')}}" method='POST'><input type='hidden'
            name='form-name' value='Spyyder' />
          <div class="group">
            <input type="text" id="firstName" name="fullname" placeholder="&nbsp;" autocomplete="off" required>
            <label for="first-name">Full name</label>
            <span class="border"></span>
          </div>
          <div class="group">
            <input type="email" name="email" placeholder="&nbsp;" autocomplete="off" required>
            <label for="email">Email</label>
            <span class="border"></span>
          </div>
          <div class="group">
            <input type="password" name="password" placeholder="&nbsp;" autocomplete="off" required>
            <label for="first-name">Password</label>
            <span class="border"></span>
          </div>
          <button type="submit" class="button">Signup</button>
        </form>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="hero">
      <h1 class="title">A stock application for</h1>
      <h1 class="title shift clip">
        <span class="word-shift">
          <b class="is-visible">beginners&nbsp;</b>
          <b>the average person</b>
          <b>learners</b>
          <b>balance</b>
          <b>everyone</b>
        </span>
      </h1>
      <div>
        <button class="button modal-toggle">Signup</button>
        <a href="{{url_for('login.root')}}"><button class="button">Login</button></a>

      </div>

      <p class="subtitle">Available for iPhone <img src="static/logo-apple.svg" alt="apple" /></p>
    </div>
    <!-- <div class="screen-wrapper">
      <img src="static/mac.png" class="screen" alt="screen" />
    </div> -->

    </section>

  </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="static/scripts.min.js"></script>
  <script>
    // Close modal on escape key
    $(document).keyup(function (e) {
      if (e.key === "Escape") {
        $('.modal').removeClass('modal-show');
        $('.content').removeClass('content-blurred');
        $('body').removeClass('no-scroll');
      }
    });

    $(function () {

      // Provider card slider
      $('.slider').flickity({
        pauseAutoPlayOnHover: false,
        prevNextButtons: false,
        cellAlign: 'center',
        draggable: false,
        freeScroll: false,
        wrapAround: true,
        pageDots: false,
        autoPlay: 3000,
      });

      // Imbox zero slider
      $('.zero-slider').flickity({
        pauseAutoPlayOnHover: false,
        prevNextButtons: false,
        cellAlign: 'center',
        freeScroll: false,
        wrapAround: false,
        draggable: false,
        pageDots: false,
        autoPlay: 3000,
        fade: true,
      });

      // Open & close modal
      $('.modal-toggle').click(function () {
        $('.modal').toggleClass('modal-show');
        $('.content').toggleClass('content-blurred');
        $('body').toggleClass('no-scroll');
      });

      // // Reserve username form
      $(".form").submit(function (e) {
        e.preventDefault();
        var $form = $(this);
        $.post($form.attr("action"), $form.serialize()).then(function () {
          $('.form-content').addClass('form-content-hide');
          $('.success').addClass('success-show');
        });
      });

      // Save user's first name
      $(".form").submit(function (e) {
        e.preventDefault();
        var value = $("#firstName").val();
        $('.first-name').text("Welcome," + " " + value + "!");
      });

      // Feather icons
      feather.replace()

      // ScrollReveal
      ScrollReveal().reveal('.hero, .title, .screen, .features, .cards, .zero-slider', {
        distance: '40px',
        duration: 2000,
        mobile: false,
        reset: false,
        opacity: 0
      });

    });
  </script>

</body>

</html>

FinalProject/webapp/application/templates/login.html
<!doctype html>
<html class="no-js h-100" lang="en">


<head>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Spyyder</title>
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" id="main-stylesheet" data-version="1.3.1" href="static/styles/shards-dashboards.1.3.1.min.css">
  <link rel="stylesheet" href="static/styles/extras.1.3.1.min.css">
  <script async defer src="https://buttons.github.io/buttons.js"></script>
</head>

<body class="h-100">
  <div class="container-fluid">
    <div class="row">
      <main class="main-content col-lg-12 col-md-12 col-sm-12 p-0">
        <div class="main-navbar  bg-white">
          <div class="container p-0">

          </div> <!-- / .container -->
        </div> <!-- / .main-navbar -->

        <div class="main-content-container container">
          <!-- Page Header -->
          <div class="page-header row no-gutters py-4">

            <div class="col-12 col-sm-4 d-flex align-items-center">

            </div>

          </div>
          <!-- End Page Header -->
          <!-- Small Stats Blocks -->
          <div class="main-content-container container-fluid px-4 my-auto h-100">
            <div class="row no-gutters h-100">
              <div class="col-lg-3 col-md-5 auth-form mx-auto my-auto">
                <div class="card">
                  <div class="card-body">
                    <img class="auth-form__logo d-table mx-auto mb-3" src="static/images/spyderlogo.png"
                      alt="Shards Dashboards - Register Template">
                    <h5 class="auth-form__title text-center mb-4">Access Your Account</h5>
                    <form action="{{url_for('login.root')}}" method='POST'>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Email address</label>
                        <input name="email" type="email" class="form-control" id="exampleInputEmail1"
                          aria-describedby="emailHelp" placeholder="Enter email">
                      </div>
                      <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input name="password" type="password" class="form-control" id="exampleInputPassword1"
                          placeholder="Password">
                      </div>
                      <div class="form-group mb-3 d-table mx-auto">
                        <div class="custom-control custom-checkbox mb-1">
                          <input type="checkbox" class="custom-control-input" id="customCheck2">
                          <label class="custom-control-label" for="customCheck2">Remember me for 30 days.</label>
                        </div>
                      </div>
                      <button type="submit" class="btn btn-pill btn-accent d-table mx-auto">Access Account</button>
                    </form>
                  </div>
                  <div class="card-footer border-top">
                    <ul class="auth-form__social-icons d-table mx-auto">
                      <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                      <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                      <li><a href="#"><i class="fab fa-github"></i></a></li>
                      <li><a href="#"><i class="fab fa-google-plus-g"></i></a></li>
                    </ul>
                  </div>
                </div>
                <div class="auth-form__meta d-flex mt-4">

                  <a href="{{url_for('index.index')}}">Home</a>
                  <a class="ml-auto" href="{{url_for('index.index')}}">Create new account?</a>
                </div>
              </div>
            </div>
          </div>

      </main>
    </div>
  </div>
  <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
    integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
  <script src="https://unpkg.com/shards-ui@latest/dist/js/shards.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Sharrre/2.0.1/jquery.sharrre.min.js"></script>
  <script src="static/scripts/extras.1.3.1.min.js"></script>
  <script src="static/scripts/shards-dashboards.1.3.1.min.js"></script>
  <script src="static/scripts/app/app-analytics-overview.1.3.1.min.js"></script>
</body>


</html>